apiVersion: v1
kind: Secret
metadata:
    name: dockerconfigjson-github-com
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2RvY2tlci5wa2cuZ2l0aHViLmNvbSI6eyJ1c2VybmFtZSI6ImxoYWlkYWNoZXIiLCJwYXNzd29yZCI6IjljODI3M2U1YjY3MmE5YWRhNzNmYTdjYTI3ZGFlNTRiZjRlYzE1YmYiLCJhdXRoIjoiYkdoaGFXUmhZMmhsY2pvNVl6Z3lOek5sTldJMk56SmhPV0ZrWVRjelptRTNZMkV5TjJSaFpUVTBZbVkwWldNeE5XSm0ifX19
